### ISSUE TITLE
【BUG】长时间使用DroidCast貌似会被杀死....

### ISSUE THREAD

**Issue by NakanoSanku** [NakanoSanku/minidevice#10]
```
Exception in thread Task:
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 793, in urlopen
  File "urllib3\connectionpool.py", line 537, in _make_request
  File "urllib3\connection.py", line 466, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 470, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 793, in urlopen
  File "urllib3\connectionpool.py", line 537, in _make_request
  File "urllib3\connection.py", line 466, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "src\app\Models\Device.py", line 32, in func
  File "src\app\Service\tasks\helpTask.py", line 30, in run
  File "src\app\Service\tasks\helpTask.py", line 37, in __check
  File "pygamescript\gamescript.py", line 27, in wrapper
  File "pygamescript\gamescript.py", line 158, in find_and_click
  File "pygamescript\gamescript.py", line 27, in wrapper
  File "pygamescript\gamescript.py", line 87, in find_and_operate
  File "pygamescript\gamescript.py", line 27, in wrapper
  File "pygamescript\gamescript.py", line 63, in find
  File "pygamescript\gamescript.py", line 27, in wrapper
  File "pygamescript\gamescript.py", line 44, in screenshot
  File "minidevice\device.py", line 55, in screenshot_raw
  File "minidevice\screencap\droidcast.py", line 68, in screencap_raw
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 682, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
具体有待测试，应设计保活部分，保证每个模块正常运行

**Comment by NakanoSanku** [comment]
daf08111da3b894bbb8f7e9b0240f534d2a31605 添加异常处理
