### ISSUE TITLE
【存疑BUG】DroidCast截图方法中，如果使用虚拟网卡时可能导致requests.adapters报错

### ISSUE THREAD

**Issue by NakanoSanku** [NakanoSanku/minidevice#5]
前段时间使用GI加速器，他弄了一个虚拟网卡
![image](https://github.com/NakanoSanku/minidevice/assets/96334375/fd1d7ffa-6ea8-474d-8842-20c6479413c6)
目前推测可能是此网卡导致的无法通过adb转发模拟器端口

- [x] 是否可稳定复现
- [x] 是否找到可靠的解决方案

重置系统网络设置后仍然存在问题，手动调试代码后恢复正常，很奇怪的bug

**Comment by NakanoSanku** [comment]
```
Traceback (most recent call last):
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\urllib3\connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\scoop\apps\miniconda3\current\Lib\http\client.py", line 1423, in getresponse
    response.begin()
  File "C:\Users\KateT\scoop\apps\miniconda3\current\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\scoop\apps\miniconda3\current\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\urllib3\connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\scoop\apps\miniconda3\current\Lib\http\client.py", line 1423, in getresponse
    response.begin()
  File "C:\Users\KateT\scoop\apps\miniconda3\current\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\scoop\apps\miniconda3\current\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KateT\PycharmProjects\GameScript\main.py", line 4, in <module>
    d = GameScript(serial="emulator-5554",capMethod=DroidCast,touchMethod=MaaTouch)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\pygamescript\gamescript.py", line 13, in __init__
    super().__init__(serial, capMethod, touchMethod, screenshotTimeout)
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\minidevice\device.py", line 36, in __init__
    self.__capMethod = capMethod(serial)
                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\minidevice\DroidCast.py", line 28, in __init__
    self.__start()
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\minidevice\DroidCast.py", line 62, in __start
    self.screencap_raw()
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\minidevice\DroidCast.py", line 73, in screencap_raw
    return self.__droidcast_session.get(self.__droidcast_url, timeout=3).content
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KateT\PycharmProjects\GameScript\venv\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by NakanoSanku** [comment]
断点调试后即可恢复正常，具体原因还没有找到
